### ISSUE TITLE
在模拟器上使用提示“资料不足”

### ISSUE THREAD

**Issue by fatinghenji** [dannyball710/UmaEventApk#1]
- 使用的版本号为1.4.7
- 使用的模拟器为夜神模拟器，版本号为7.0.1.9，安卓版本为：android9,64位
- 这是其中的一个无法识别的图片：
![last_screenshot](https://user-images.githubusercontent.com/37131177/145758891-9f6bb1b8-dc5b-4a86-965f-b7e25e3aa51b.png)
  - 小栗帽的一个人物养成事件，应该不是近期加入的新事件。
- 这是一个已知的bug吗？需要我提供进一步的资料吗？如果需要的话可以说明如何提供吗？

**Comment by dannyball710** [comment]
這是模擬器的缺陷，使用android原生的截圖方式在夜神上會全黑，回報給官方也沒下文...
